In [1]:
import json
import argparse
import torch
import difflib
import nltk
import regex as re
import numpy as np
import MeCab
import pickle

from tqdm import tqdm
from collections import defaultdict
from transformers import AutoModelForMaskedLM, AutoTokenizer

In [4]:
female_inputs = pickle.load(open('zh_f.bin', 'rb'))
female_inputs

[tensor([[  101, 12423,  6134,  4850,  8038,   102]], device='cuda:0'),
 tensor([[ 101, 8174,  158, 8159, 9917, 6371,  711, 8024,  102]],
        device='cuda:0'),
 tensor([[ 101, 1762, 1059, 2349, 1825, 3172, 1767, 8024,  102]],
        device='cuda:0'),
 tensor([[ 101, 1957,  782, 1377, 5543,  100,  102]], device='cuda:0'),
 tensor([[  101,  2190,   818,   862,  6371,  6399, 11701,  4638,   782,  3341,
           6432,  8024,   102]], device='cuda:0'),
 tensor([[  101,  1300,  2145,  8412, 10551,  8937,  1156,  6391,  1173,  1765,
           6371,   711,  8038,   102]], device='cuda:0'),
 tensor([[  101,  9622, 11541, 11541,  8343,   100,   800,  6158,  1161,  1152,
           8110,  2399,  1348,   127,   702,  3299,  8024,   102]],
        device='cuda:0'),
 tensor([[ 101,  738, 3300,  816, 1280, 1399, 4522, 6241, 3118, 2898, 1333, 1440,
          8038,  102]], device='cuda:0'),
 tensor([[ 101, 1300, 2145,  680, 3696,  830, 1762, 4852, 5408, 5381, 4991, 3141,
          3064, 1812, 1